[package]
name = "pippin"
version = "0.0.0"
authors = ["Diggory Hardy <github1@dhardy.name>"]

[dependencies]

rust-crypto = "*"
# possible alternatives: sha, shaman

chrono = "*"

# Not yet stable, and not essential:
# simd = "*"

byteorder ="*"
