[package]
authors = ["Diggory Hardy <git@dhardy.name>"]
name = "pippin_app_tests"
version = "0.0.0"

[lib]
name = "pippin_app_tests"
path = "app_tests_lib.rs"

[dependencies]
pippin = { path = ".." }
